USE master;

IF EXISTS(SELECT * FROM sys.databases WHERE name='db01')
BEGIN
	ALTER DATABASE db01 SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE db01;
END

CREATE DATABASE db01;
GO

USE db01;

CREATE TABLE dbo.Test
(id int PRIMARY KEY)

GO