USE db01;
/*
DROP TABLE IF EXISTS dbo.Test;
CREATE TABLE dbo.Test(id int PRIMARY KEY)
*/

dbcc useroptions;

SET TRANSACTION ISOLATION LEVEL READ UNCOMMITTED
SET TRANSACTION ISOLATION LEVEL READ COMMITTED
SET TRANSACTION ISOLATION LEVEL REPEATABLE READ
SET TRANSACTION ISOLATION LEVEL SERIALIZABLE

SET TRANSACTION ISOLATION LEVEL SNAPSHOT

ALTER DATABASE [db01] SET ALLOW_SNAPSHOT_ISOLATION ON
GO


BEGIN TRAN;

SELECT * FROM dbo.Test;

WAITFOR DELAY '0:0:10';

SELECT * FROM dbo.Test;

COMMIT TRAN;


