USE master;

IF EXISTS(SELECT * FROM sys.databases WHERE name='db01')
BEGIN
	ALTER DATABASE db01 SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
	DROP DATABASE db01;
END

CREATE DATABASE db01;
GO

USE db01;

USE [master]
GO

ALTER DATABASE [db01] ADD FILEGROUP [MOD] CONTAINS MEMORY_OPTIMIZED_DATA 
ALTER DATABASE [db01] ADD FILE ( NAME = N'db01_mod', FILENAME = N'C:\SQLData\SQL2\db01_mod' ) TO FILEGROUP [MOD]
GO

USE db01;


CREATE TABLE dbo.Test01
(
	test_id int IDENTITY(1, 1),
	test_data1 nvarchar(50), 
	test_data2 nvarchar(50), 

   CONSTRAINT PK_Test01 PRIMARY KEY NONCLUSTERED (test_id),
   INDEX hasth_test_id HASH (test_id) WITH (BUCKET_COUNT = 10000)
) WITH (MEMORY_OPTIMIZED = ON, DURABILITY = SCHEMA_AND_DATA) --DURABILITY=SCHEMA_ONLY
GO

SELECT @@VERSION;