USE tempdb;

CREATE TABLE dbo.Map
(
id int PRIMARY KEY,
map1 geography,
map2 geometry
)

USE [tempdb]

GO

CREATE SPATIAL INDEX [spi_map1] ON [dbo].[Map]
(
	[map1]
)USING  GEOGRAPHY_GRID 
WITH (GRIDS =(LEVEL_1 = MEDIUM,LEVEL_2 = MEDIUM,LEVEL_3 = MEDIUM,LEVEL_4 = MEDIUM), 
CELLS_PER_OBJECT = 16, PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

GO

CREATE SPATIAL INDEX [spi_map2] ON [dbo].[Map]
(
	[map2]
)USING  GEOMETRY_AUTO_GRID 
WITH (BOUNDING_BOX =(0, 0, 100, 100), 
CELLS_PER_OBJECT = 16, PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON)

GO

